@startuml VocabularyConceptualModelMain

object Game
object Turn
object PlayerTurn

object Player
object TypeOfPlayer

Player --o{ PlayerTurn
Turn --|{ PlayerTurn
Game --o{ Turn
TypeOfPlayer --|| Player

/' Tic Tac Toe'/
object Board
object Box
object TicTacToeTurn

TicTacToeTurn -left-o{ Board
Board -left-|{ Box

/' HangMan'/
object HangManTurn
object HangedMan
object SecretWord

HangManTurn -right-o{  HangedMan
HangedMan -right-|{ SecretWord

PlayerTurn --|{ TicTacToeTurn
PlayerTurn --|{ HangManTurn
@enduml