@startuml VocabularyLogicModelMain

entity Game
{
    * id_Game : number <<generated>>
    --
    * gameName: varchar2(15)
}
entity Turn
{
    * id_Turn : number <<generated>>
    --
    * id_Game : number
    * turns : number
    * players : number
}
entity PlayerTurn
{
    * id_PlayerTurn : number <<generated>>
    --
    * id_Turn : number
    * id_Player : number
}

entity Player
{
    * id_Player : number <<generated>>
    --
    * playerName :  varchar2(50)
    * winPoints : number
    * loosePoints : number
    * id_TypeOfPlayer : number
}

entity TypeOfPlayer
{
    * id_TypeOfPlayer : number <<generated>>
    --
    * TypeOfPlayer: varchar2(25)
}

TypeOfPlayer -left-|| Player
Player --o{ PlayerTurn
Game -right-o{ Turn
    
Turn --|{ PlayerTurn

/' Tic Tac Toe'/ 
entity TicTacToeTurn {
    * id_TicTacToeTurn : number <<generated>>
    --
    * PieceX : number
    * PieceO : number
}
entity Board {
    * id_Board : number <<generated>>
    --
    * id_TicTacToeTurn : number
    * freePositions : number
}
entity Box{
    * id_Box : number <<generated>>
    --
    * id_Board : number 
    * boxesX :  number
    * boxesO :  number
    * piece : varchar2(10)
}

/' HangMan'/
entity HangManTurn
{
    * id_HangManTurn : number <<generated>>
    --
    * giver : number
    * guesser : number
}
entity HangedMan
{
    * id_HangedMan: number
    --
    * id_HangManTurn : number
     completed : boolean
}
entity SecretWord
{
    * id_SecretWord : number <<generated>>
    --
    * id_HangedMan: number
    * letters : varchar2(15)
    * possitions : number
}

PlayerTurn --|{ TicTacToeTurn
PlayerTurn --|{ HangManTurn

TicTacToeTurn -left-o{ Board
Board -left-|{ Box

HangManTurn -right-o{  HangedMan
HangedMan -right-|{ SecretWord
@enduml