@startuml VocabularyConceptualModelMain

object round
object turn
object player
object hangManPlayer
object ticTacToePlayer
object typeGame
object typeOfPlayer

player --|{ typeGame
typeGame --|{ ticTacToePlayer
typeGame --|{ hangManPlayer

round -left-|{ turn

ticTacToePlayer --|| round

player --|| typeOfPlayer
@enduml