@startuml VocabularyLogicModelMain

entity round {
    * id_round : number <<generated>>
    --
}
entity turn
{
    * id_turn : number <<generated>>
    --
}
entity player
{
    * id_player : number <<generated>>
    --
    * playerName :  varchar2(50)
    * id_typeOfPlayer : number
}
entity typeOfPlayer {
    * id_typeOfPlayer : number <<generated>>
    --
    * typeOfPlayer: varchar2(25)
}


entity typeGame
{
     * id_typeGame : number <<generated>>
    --
    * typeGame: varchar2(25)
}

player -up-|{ typeGame
round --|{ turn
player -left-|| round
player --|| typeOfPlayer

/' Tic Tac Toe'/
entity board {
    * id_Board : number <<generated>>
    * freePositions : number
}
entity piece{
    *id_piece : number <<generated>>
    *piece : varchar2(1)
}

board --|{piece
player --|{piece


/' HangMan'/

entity word {
    * id_Word : number <<generated>>
    --
    * secretWord varchar2(50)
    * guessedWord varchar2(50)
}

player --|{word



@enduml