@startuml VocabularyConceptualModelM

entity typeOfPlayer {
    * id_typeOfPlayer : number <<generated>>
    --
    * typeOfPlayer: varchar2(25)
}

entity player {
    * id_Player : number <<generated>>
    --
    * id_typeOfPlayer : number
}

entity word {
    * id_Word : number <<generated>>
    --
    * secretWord varchar2(50)
    * guessedWord varchar2(50)
}

player --||typeOfPlayer
player --|{word
@enduml